### ISSUE TITLE
Meet Page 구상

### ISSUE THREAD

**Issue by eunjung0613** [S-CON-SKHU/ContestCollection-Web#28]
### 설명

화상 회의 서비스 구현을 위한 페이지 구축을 시작합니다.

### Task

- [ ]  컴포넌트 파일 설정
- [x] 라우터 설정을 통한 페이지 설정
- [x] 구현 이전 요소 위치 배치 진행

**Comment by eunjung0613** [comment]
![image](https://user-images.githubusercontent.com/37800677/162031181-4a773ebb-e7e5-4dff-90fa-052cc2d7a9c6.png)

🖤  라우터 설정 진행
🖤 구현하고자 하는 위치 지정 중

**Comment by eunjung0613** [comment]
![image](https://user-images.githubusercontent.com/37800677/162144742-40266cdd-b658-40cd-8d58-ae6e8408f6f1.png)

🖤 상기 위치 기준 textarea readonly 로 차후 link 생성하여 기재할 장소 생성
🖤 버튼 클릭 시 알림 발생 / 실제 복사 진행 확인 완료

**Comment by hanseulhee** [comment]
기능 좋은 것 같아요 👍👍👍👍
웹 디자인만 하면 될 것 같아요 ~!!
