### ISSUE TITLE
Write Page 변경

### ISSUE THREAD

**Issue by eunjung0613** [S-CON-SKHU/ContestCollection-Web#55]
### 설명

Write Page의 입력을 축소하여 지정된 양식에 맞추어 엑셀 입력시, 엑셀의 값을 불러와 서버로 전달 할 수 있도록 변경합니다.

### Task

- [x] write page 폼 변경
- [x] form에 정상적인 업로드가 되는지 확인
- [x] 서버 연동 후 전달 확인
- [ ] 최종 디자인 진행

**Comment by eunjung0613** [comment]
📁  form 태그 전체 변경 진행 후 excel 파일 업로드 시, 파일 이름을 useState로 변경 관리
📁 excel을 배열로 변경 후 console.log를 통한 확인
📁 axios를 통해 생성한 배열이 서버로 전달되는지 test ➡️ RestAPI 생성 후 작업 가능할 것으로 확인

![result](https://user-images.githubusercontent.com/37800677/168202141-0ce6a329-074d-4882-963d-d837e1bb8dc9.gif)

**Comment by eunjung0613** [comment]
📁디자인 변경, 로고 추가를 통한 main 페이지로 이동 확인
📁framer motion을 통한 슬라이드 애니메이션 추가

![formstyle](https://user-images.githubusercontent.com/37800677/169943768-4fcb00d5-37bc-4c69-a657-cc3c4f7b7c2f.gif)

**Comment by eunjung0613** [comment]
피드백 이후 수정예정사항

📁 엑셀파일을 front에서 파싱하지 말고 excel 그대로 서버로 전달 예정 ➡️ 코드 수정 예정
- [x] post 코드 수정

**Comment by eunjung0613** [comment]
📁엑셀파일 front에서 받아 서버로 post 진행 완료 ➡️ 현재 React CORS 오류 발생되어 이후 서버측 수정될 경우 setText와 다른 작업 진행 예정
📁 lottie 사용을 통한 애니메이션 추가

![modify](https://user-images.githubusercontent.com/37800677/169971368-886b93a3-2da1-4003-a3c9-f92374b2776d.gif)

@hanseulhee

**Comment by hanseulhee** [comment]
디자인 귀여워요 ㅋㅋㅋㅋㅋ 😮 framer motion 까지 👍👍👍
