### ISSUE TITLE
mainpage 개발

### ISSUE THREAD

**Issue by eunjung0613** [S-CON-SKHU/ContestCollection-Web#7]
### 설명

main page 개발, scon에 대한 설명 작성 및 전체적인 태그 작성 진행

### Task

- [x] 메인 페이지 내용 중 스콘에 대한 설명 작성 완료
- [x] 메인 페이지 내용 중 사용법 작성 완료
- [x] 개발자 소개 작성 완료 
- [x] Lottie를 통한 이미지 작성 후 메인페이지 완성
